// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28_7ZBukEcJgkBtbn16e5YLiolK5uR9Q',
    appId: '1:596818659834:web:7f0b9b035608f2906c7c43',
    messagingSenderId: '596818659834',
    projectId: 'student-management-syste-54e39',
    authDomain: 'student-management-syste-54e39.firebaseapp.com',
    storageBucket: 'student-management-syste-54e39.firebasestorage.app',
    measurementId: 'G-RK4HRWX9JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyw7L6B0s6SM3KZb1_vYeXFFAbQYQnXyU',
    appId: '1:596818659834:android:36f4123b0ac70c306c7c43',
    messagingSenderId: '596818659834',
    projectId: 'student-management-syste-54e39',
    storageBucket: 'student-management-syste-54e39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxyl1drmskko11uAKRqykZIEUzNRx91pc',
    appId: '1:596818659834:ios:41c951f4ca7218c16c7c43',
    messagingSenderId: '596818659834',
    projectId: 'student-management-syste-54e39',
    storageBucket: 'student-management-syste-54e39.firebasestorage.app',
    iosBundleId: 'com.example.fatmaElorbany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB28_7ZBukEcJgkBtbn16e5YLiolK5uR9Q',
    appId: '1:596818659834:web:07b1d338c3a6f52a6c7c43',
    messagingSenderId: '596818659834',
    projectId: 'student-management-syste-54e39',
    authDomain: 'student-management-syste-54e39.firebaseapp.com',
    storageBucket: 'student-management-syste-54e39.firebasestorage.app',
    measurementId: 'G-BVP3VJB69P',
  );
}
